name: Build CI Test

on:
  push:
    branches:
      - ciTest/simulation-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "Build CI Test workflow executed!" 