name: Trigger On Workflow Run

on:
  workflow_run:
    workflows: ["Build CI Test"]
    types:
      - completed

jobs:
  on_workflow_run:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Echo triggered
        run: echo "Triggered by Build CI Test workflow_run!"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: example-artifact2

      - name: Show artifact content
        run: cat example.txt